name: TheShark34/Sandstone
author:
  name: Adrien Navratil
  email: adrien1975@live.fr
  url: 'http://theshark34.github.io/'
copyright: 2015 Adrien Navratil
description: Bringing forge-like ASM to Bukkit.
